version: '3.8'
services:
  root:
    build:
      context: .
      dockerfile: ./apps/root/Dockerfile
    ports:
      - 5000:5000
    env_file:
      - .env
    environment:
      - MODE=production
    image: z3r0c0d3r/root:0.0.2
    depends_on:
      - subscriptions
  subscriptions:
    build:
      context: .
      dockerfile: ./apps/subscriptions/Dockerfile
    env_file:
      - .env
    environment:
      - MODE=production
    image: z3r0c0d3r/subscriptions:0.0.4
  rabbitmq:
    image: rabbitmq:3-management
    restart: always