version: '3.8'
services:
  root:
    build:
      context: .
      dockerfile: ./apps/root/Dockerfile
    ports:
      - 5000:5000
    env_file:
      - .env
    environment:
      - MODE=production
    image: z3r0c0d3r/root:0.0.4
    depends_on:
      - rabbitmq
      - subscriptions
  subscriptions:
    build:
      context: .
      dockerfile: ./apps/subscriptions/Dockerfile
    ports:
      - 6000:6000
    env_file:
      - .env
    environment:
      - MODE=production
    image: z3r0c0d3r/subscriptions:0.0.6
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672
      - 15672:15672
  admin:
    build:
      context: .
      dockerfile: ./apps/admin/Dockerfile
    ports:
      - 7000:7000
    env_file:
      - ./apps/admin/.env
    environment:
      - MODE=production
    image: z3r0c0d3r/admin:0.0.3
    depends_on:
      - rabbitmq